# Generated by Django 3.1.1 on 2020-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationproduct',
            name='sold_out',
            field=models.IntegerField(default=0),
        ),
    ]
