# Generated by Django 3.1.1 on 2020-11-11 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201111_0039'),
        ('location', '0002_locationproduct_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationproduct',
            name='variation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='product.variation'),
        ),
        migrations.AlterField(
            model_name='locationproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='product.product'),
        ),
    ]
