# Generated by Django 3.1.1 on 2020-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='buying_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='gtin',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='margin',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='markup',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='number_of_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='sku',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='threshold_stock',
            field=models.IntegerField(default=0),
        ),
    ]
