# Generated by Django 3.1.1 on 2020-11-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_variation_available_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sold_out',
            field=models.IntegerField(default=0),
        ),
    ]
