# Generated by Django 3.1.1 on 2020-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201111_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
