# Generated by Django 3.1.1 on 2020-11-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201111_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvalue',
            name='option',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
