# Generated by Django 3.1.1 on 2020-11-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201111_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name',)},
        ),
    ]
