# Generated by Django 3.1.1 on 2020-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20201111_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionValue',
        ),
        migrations.AddField(
            model_name='option',
            name='values',
            field=models.JSONField(default=dict),
        ),
    ]
