# Generated by Django 3.1.1 on 2020-11-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201111_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='products',
        ),
    ]
