# Generated by Django 3.1.1 on 2020-11-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20201111_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
