# Generated by Django 3.1.1 on 2020-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_delete_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='markup',
            new_name='profit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='buying_price',
            new_name='regular_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='buying_price',
            new_name='regular_price',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='selling_price',
            new_name='sale_price',
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='barcode',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
