# Generated by Django 3.1.1 on 2020-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20201112_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='threshold_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='number_of_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sold_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='threshold_stock',
            field=models.IntegerField(default=0),
        ),
    ]
