# Generated by Django 3.1.1 on 2020-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20201112_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_stock',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_out',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='threshold_stock',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='available_stock',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='number_of_stock',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='regular_price',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sale_price',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sold_out',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='threshold_stock',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
    ]
