# Generated by Django 3.1.1 on 2020-11-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20201112_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_item',
            field=models.TextField(default='0', max_length=2000, null=True),
        ),
    ]
