# Generated by Django 3.1.1 on 2020-11-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_cost_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_unit',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_unit',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_unit',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
