# Generated by Django 3.1.1 on 2020-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category2',
            name='icon',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='category2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/category2/'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
